version: '3'
networks:
  default:
    external:
      name: prog_net
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data 
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    image: prog_image_application
    volumes:
      - .:/prog_image
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    links:
      - redis
      - sidekiq  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"   
  sidekiq:
    depends_on:
      - redis
      - db
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/prog_image
    env_file:
      - .env 
    environment:
      RAILS_ENV: development
      REDIS_URL: "redis://redis:6379/12" 
      DB_HOST: db
      DB_USER: postgres
      DB_NAME: prog_image_development
     
